POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "jeff",
    "email": "jeffrey3311@amazon.com",
    "password": "1@aBcdefg"
}
###
POST http://localhost:5000/api/goals HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFlYTg4NDBhZDJiOWY1NTViYWM5N2EiLCJpYXQiOjE2OTY1MDgwMzYsImV4cCI6MTY5Njc2NzIzNn0.cJkluSNwmFdrus7DjDUEX7nPmpBAGMxo7mPCP2Ag4ek
Content-Type: application/json

{
    "text": "example goal"
}
###
GET http://localhost:5000/api/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFlYTg4NDBhZDJiOWY1NTViYWM5N2EiLCJpYXQiOjE2OTY1MDgwMzYsImV4cCI6MTY5Njc2NzIzNn0.cJkluSNwmFdrus7DjDUEX7nPmpBAGMxo7mPCP2Ag4ek
